"""
Optimized GSGWR Estimation Code for Large-Sample Datasets (Exemplified with Housing Data)
Paper: Geographical Similarity and Geographically Weighted Regression (GSGWR): Operationalizing the Second Law of Geography in a Regression Framework by Integrating the First and Third Laws

# Repository Folder Structure
The entire repository consists of two top-level folders:

1. /GSGWR/ (this code folder)
   - `GSGWR_Housing.py`: Optimized batch‑processing and memory‑saving version of GSGWR, designed specifically for large‑sample datasets (here applied to the Housing dataset as an example).
   - `GSGWR_main.py`: Standard GSGWR script for small‑ to medium‑sized datasets (zn, Crime, HIV, Depression).
   - `Preprocess_GeoMatrix.py`: Generates the geographical spatial distance matrix.
   - `Preprocess_SimMatrix.py`: Generates the attribute similarity distance matrix.

2. /Data/ (sibling folder of /GSGWR/, stores all raw data and matrix outputs)
   - `Housing.csv`: Raw housing price dataset.
   - `Geographical_distance_matrix.csv`: Large spatial distance matrix generated by the preprocessing code.
   - `Similarity_distance_matrix.csv`: Large attribute similarity distance matrix generated by the preprocessing code.

# Key Differences Between the Two GSGWR Scripts
1. Core Model Mathematics: Both scripts use the same Gaussian kernel, leave‑one‑out cross‑validation (LOO‑CV) loss function, and local weighted regression formulation; there is no difference in model specification.
2. Optimization Design (for large‑sample data, such as this Housing dataset):
   - Numba JIT acceleration for kernel and weight calculations;
   - Batch‑by‑batch local model fitting to control RAM usage;
   - Chunked loading of large matrices to avoid memory overflow;
   - A four‑stage finer bandwidth refinement search to avoid local CV minima in dense large‑sample settings.
   *Note: The standard script `GSGWR_main.py` can load the full matrix directly for small‑ to medium‑sized datasets (N < 3000), where three rounds of coarse‑to‑fine bandwidth search suffice. For large‑sample data (e.g., N ≈ 20,000 in this example), using the standard script would result in slow computation and potential memory exhaustion, hence the need for the optimizations above.*
3. Use Case for `GSGWR_main.py`:
   Suitable for small‑ to medium‑sized datasets (N < 3000, e.g., zn, Crime, HIV, Depression). Full matrix loading is feasible; three rounds of coarse‑to‑fine bandwidth search are sufficient, and additional refinement stages would incur redundant computational cost.

# Full Reproduction Workflow for the Housing Dataset
1. First generate the two large distance matrix files
   Run the two preprocessing scripts located in `/GSGWR/`:
   - `Preprocess_GeoMatrix.py` outputs `Geographical_distance_matrix.csv`, saved to `../Data/`
   - `Preprocess_SimMatrix.py` outputs `Similarity_distance_matrix.csv`, saved to `../Data/`

2. Run this script directly – no manual filename modification is needed (pre‑configured for the Housing data)
   - Mode 1: Full four‑stage bandwidth optimization (reproduces the complete CV search process).
   - Mode 2: Fast fitting using pre‑estimated optimal bandwidths (the actual values should be determined by searching over the data or by roughly assessing the matrix ranges; the numbers here are for illustration only).

3. Output Storage
   All batch‑wise local coefficients, predicted values, residuals, and evaluation metrics will be automatically saved to the `./output_housing/` folder inside `/GSGWR/`.
"""
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator
from sklearn.preprocessing import StandardScaler
import warnings
import gc
from scipy.spatial.distance import cdist
import numba
import os

warnings.filterwarnings('ignore')


class GSGWR_Optimized(BaseEstimator):
    """
    Memory-optimized GSGWR model
    """

    def __init__(self, h_s=0.074347, h_a=10.504064, batch_size=500):
        self.h_s = h_s
        self.h_a = h_a
        self.batch_size = batch_size
        self.coef_ = None
        self.intercept_ = None
        self.local_coef_ = None
        self.X_scaler = None
        self.Y_scaler = None

    @staticmethod
    @numba.jit(nopython=True, fastmath=True)
    def _gaussian_kernel(d, h):
        return np.exp(-(d ** 2) / (h ** 2))

    @staticmethod
    @numba.jit(nopython=True, fastmath=True)
    def _compute_weights_vector(distances, similarities, h_s, h_a):
        w_s = np.exp(-(distances ** 2) / (h_s ** 2))
        w_a = np.exp(-(similarities ** 2) / (h_a ** 2))
        return w_s * w_a

    def fit_local_model_batch(self, X, Y, D_s, D_a, batch_indices):
        """Fit local models in batch"""
        n_samples = len(batch_indices)
        n_features = X.shape[1]
        batch_coef = np.zeros((n_samples, n_features + 1))

        X_design = np.column_stack([np.ones(X.shape[0]), X])

        for i, idx in enumerate(batch_indices):
            distances = D_s[:, idx]
            similarities = D_a[:, idx]
            weights = self._compute_weights_vector(distances, similarities, self.h_s, self.h_a)

            W_sqrt = np.sqrt(weights)
            X_weighted = W_sqrt.reshape(-1, 1) * X_design
            Y_weighted = W_sqrt * Y

            try:
                beta = np.linalg.lstsq(X_weighted, Y_weighted, rcond=1e-6)[0]
                batch_coef[i] = beta
            except np.linalg.LinAlgError:
                batch_coef[i, 0] = np.average(Y, weights=weights)

            if (i + 1) % 100 == 0:
                print(f"    Completed {i + 1}/{n_samples} local models in this batch")

        return batch_coef

    def fit(self, X, Y, D_s, D_a):
        """Fit model in batches"""
        n_samples = X.shape[0]
        n_features = X.shape[1]

        print(f"Starting batch fitting, batch size: {self.batch_size}, total samples: {n_samples}")

        self.local_coef_ = np.zeros((n_samples, n_features + 1))

        for start_idx in range(0, n_samples, self.batch_size):
            end_idx = min(start_idx + self.batch_size, n_samples)
            batch_indices = range(start_idx, end_idx)

            print(f"Processing batch: {start_idx}-{end_idx - 1}")

            batch_coef = self.fit_local_model_batch(X, Y, D_s, D_a, batch_indices)
            self.local_coef_[start_idx:end_idx] = batch_coef

            gc.collect()

        self.coef_ = np.mean(self.local_coef_[:, 1:], axis=0)
        self.intercept_ = np.mean(self.local_coef_[:, 0])

        print("Model fitting completed!")
        return self

    def predict(self, X):
        if self.local_coef_ is None:
            raise ValueError("Model has not been trained yet")

        X_design = np.column_stack([np.ones(X.shape[0]), X])
        y_pred = np.sum(X_design * self.local_coef_, axis=1)
        return y_pred

    def loocv_score(self, X, Y, D_s, D_a):
        """Leave-one-out cross-validation score"""
        n_samples = X.shape[0]
        y_pred_cv = np.zeros(n_samples)

        print("Performing leave-one-out cross-validation...")

        for i in range(n_samples):
            if (i + 1) % 100 == 0:
                print(f"  LOOCV progress: {i + 1}/{n_samples}")

            mask = np.ones(n_samples, dtype=bool)
            mask[i] = False

            X_train = X[mask]
            Y_train = Y[mask]
            distances = D_s[mask, i]
            similarities = D_a[mask, i]

            weights = self._compute_weights_vector(distances, similarities, self.h_s, self.h_a)

            X_design = np.column_stack([np.ones(X_train.shape[0]), X_train])
            W_sqrt = np.sqrt(weights)

            X_weighted = W_sqrt.reshape(-1, 1) * X_design
            Y_weighted = W_sqrt * Y_train

            try:
                beta = np.linalg.lstsq(X_weighted, Y_weighted, rcond=1e-6)[0]
                y_pred_cv[i] = beta[0] + np.dot(X[i], beta[1:])
            except np.linalg.LinAlgError:
                y_pred_cv[i] = np.average(Y_train, weights=weights)

        mse = np.mean((Y - y_pred_cv) ** 2)
        return mse

    def score(self, X, Y, D_s=None, D_a=None):
        y_pred = self.predict(X)
        return np.mean((Y - y_pred) ** 2)


class BandwidthOptimizer:

    def __init__(self, batch_size=500):
        self.batch_size = batch_size
        self.best_score = float('inf')
        self.best_params = None
        self.search_history = []

    def evaluate_bandwidth_loocv(self, h_s, h_a, X, Y, D_s, D_a):
        try:
            model = GSGWR_Optimized(h_s=h_s, h_a=h_a, batch_size=self.batch_size)
            score = model.loocv_score(X, Y, D_s, D_a)

            del model
            gc.collect()

            return score
        except Exception as e:
            print(f"Bandwidth evaluation failed for h_s={h_s:.6f}, h_a={h_a:.6f}: {e}")
            return float('inf')

    def coarse_search(self, X, Y, D_s, D_a):
        """Coarse search"""
        print("Starting coarse search...")

        D_s_quantiles = np.percentile(D_s, [5, 25, 50, 75, 95])
        D_a_quantiles = np.percentile(D_a, [5, 25, 50, 75, 95])

        h_s_coarse = np.linspace(D_s_quantiles[0] * 0.5, D_s_quantiles[4] * 2, 9)
        h_a_coarse = np.linspace(D_a_quantiles[0] * 0.5, D_a_quantiles[4] * 2, 9)

        best_score = float('inf')
        best_h_s, best_h_a = h_s_coarse[0], h_a_coarse[0]

        total_combinations = len(h_s_coarse) * len(h_a_coarse)
        current_combination = 0

        for i, h_s in enumerate(h_s_coarse):
            for j, h_a in enumerate(h_a_coarse):
                current_combination += 1
                print(f"  Coarse search progress: {current_combination}/{total_combinations}")

                score = self.evaluate_bandwidth_loocv(h_s, h_a, X, Y, D_s, D_a)
                self.search_history.append({
                    'h_s': h_s, 'h_a': h_a, 'score': score, 'stage': 'coarse'
                })

                print(f"    h_s={h_s:.6f}, h_a={h_a:.6f}, LOOCV_MSE={score:.6f}")

                if score < best_score:
                    best_score = score
                    best_h_s, best_h_a = h_s, h_a
                    print(f"    ↑ New best solution! LOOCV_MSE={best_score:.6f}")

        print(f"Coarse search completed: best h_s={best_h_s:.6f}, h_a={best_h_a:.6f}, LOOCV_MSE={best_score:.6f}")
        return best_h_s, best_h_a, best_score

    def fine_search_round(self, X, Y, D_s, D_a, base_h_s, base_h_a,
                          range_ratio, n_points, round_name):
        """Single fine search round"""
        print(f"\nStarting {round_name}...")

        h_s_range = np.linspace(base_h_s * (1 - range_ratio),
                                base_h_s * (1 + range_ratio), n_points)
        h_a_range = np.linspace(base_h_a * (1 - range_ratio),
                                base_h_a * (1 + range_ratio), n_points)


        best_score = float('inf')
        best_h_s, best_h_a = base_h_s, base_h_a

        total_combinations = len(h_s_range) * len(h_a_range)
        current_combination = 0

        for i, h_s in enumerate(h_s_range):
            for j, h_a in enumerate(h_a_range):
                current_combination += 1
                print(f"  {round_name} progress: {current_combination}/{total_combinations}")

                score = self.evaluate_bandwidth_loocv(h_s, h_a, X, Y, D_s, D_a)
                self.search_history.append({
                    'h_s': h_s, 'h_a': h_a, 'score': score, 'stage': round_name
                })

                print(f"    h_s={h_s:.6f}, h_a={h_a:.6f}, LOOCV_MSE={score:.6f}")

                if score < best_score:
                    best_score = score
                    best_h_s, best_h_a = h_s, h_a
                    print(f"    ↑ New best solution! LOOCV_MSE={best_score:.6f}")

        print(f"{round_name} completed: best h_s={best_h_s:.6f}, h_a={best_h_a:.6f}, LOOCV_MSE={best_score:.6f}")
        return best_h_s, best_h_a, best_score

    def optimize(self, X, Y, D_s, D_a):
        """Perform complete bandwidth optimization"""
        print("=" * 60)
        print("Starting bandwidth optimization (using leave-one-out cross-validation)...")
        print("=" * 60)

        best_h_s, best_h_a, best_score = self.coarse_search(X, Y, D_s, D_a)

        search_params = [
            (0.4, 7, "First round fine search"),
            (0.2, 7, "Second round fine search"),
            (0.1, 5, "Third round fine search"),
            (0.05, 5, "Fourth round fine search")
        ]

        for range_ratio, n_points, round_name in search_params:
            best_h_s, best_h_a, best_score = self.fine_search_round(
                X, Y, D_s, D_a, best_h_s, best_h_a, range_ratio, n_points, round_name
            )

        self.best_score = best_score
        self.best_params = {'h_s': best_h_s, 'h_a': best_h_a}

        print("\n" + "=" * 60)
        print("Bandwidth optimization completed!")
        print(f"Final optimal parameters: h_s={best_h_s:.6f}, h_a={best_h_a:.6f}")
        print(f"Final optimal LOOCV_MSE: {best_score:.6f}")
        print("=" * 60)

        return best_h_s, best_h_a


def load_matrix_chunked(filepath, n_samples, chunk_size=1000):
    """Load large distance matrix in chunks"""
    print(f"Loading matrix in chunks: {filepath}")
    print(f"Number of samples: {n_samples}, chunk size: {chunk_size}")

    matrix = np.zeros((n_samples, n_samples))
    chunks_loaded = 0

    for start_row in range(0, n_samples, chunk_size):
        end_row = min(start_row + chunk_size, n_samples)

        chunk = pd.read_csv(filepath, header=0, skiprows=start_row,
                            nrows=chunk_size, dtype=np.float32)

        if chunk.shape[1] > n_samples:
            chunk = chunk.iloc[:, :n_samples]
        elif chunk.shape[1] < n_samples:
            padding = np.zeros((chunk.shape[0], n_samples - chunk.shape[1]), dtype=np.float32)
            chunk = pd.concat([chunk, pd.DataFrame(padding)], axis=1, ignore_index=True)

        chunk_values = chunk.values.astype(np.float32)

        if np.any(np.isnan(chunk_values)):
            nan_count = np.sum(np.isnan(chunk_values))
            print(f"  Chunk {chunks_loaded + 1} contains {nan_count} NaN values, filling with 0")
            chunk_values = np.nan_to_num(chunk_values)

        rows_to_fill = min(chunk_values.shape[0], n_samples - start_row)
        matrix[start_row:start_row + rows_to_fill, :] = chunk_values[:rows_to_fill, :]

        chunks_loaded += 1
        if chunks_loaded % 10 == 0:
            print(f"  Loaded {chunks_loaded} chunks")

    print(f"Matrix loading completed, total {chunks_loaded} chunks loaded")
    return matrix.astype(np.float32)


def load_all_data():
    """Load all data"""
    try:
        main_data_path = '../Data/Housing.csv'
        geo_matrix_path = '../Data/Geographical_distance_matrix.csv'
        sim_matrix_path = '../Data/Similarity_distance_matrix.csv'

        all_data = pd.read_csv(main_data_path)
        print(f"All data shape: {all_data.shape}")
        print("Data columns:", all_data.columns.tolist())

        # Columns 1-4 are coordinates, column 5 is dependent variable, columns 6+ are independent variables
        coords = all_data.iloc[:, 0:4].values
        Y = all_data.iloc[:, 4].values
        X = all_data.iloc[:, 5:].values
        # Extract independent variable column names for later dynamic header generation
        x_col_names = all_data.columns[5:].tolist()

        print(f"Coordinates shape: {coords.shape}")
        print(f"Dependent variable shape: {Y.shape}")
        print(f"Independent variables shape: {X.shape}")

        n_samples = len(Y)
        print(f"Number of samples: {n_samples}")

        print("Reading spatial distance matrix...")
        D_s = load_matrix_chunked(geo_matrix_path, n_samples, chunk_size=1000)

        print("Reading attribute similarity matrix...")
        D_a = load_matrix_chunked(sim_matrix_path, n_samples, chunk_size=1000)

        print(f"Spatial distance matrix shape: {D_s.shape}")
        print(f"Attribute similarity matrix shape: {D_a.shape}")

        if D_s.shape != (n_samples, n_samples) or D_a.shape != (n_samples, n_samples):
            raise ValueError(f"Distance matrix dimensions are incorrect")

        # Return independent variable column names as well
        return X, Y, D_s, D_a, coords, x_col_names

    except Exception as e:
        print(f"Data loading error: {e}")
        print("=== Troubleshooting tips ===")
        print("1. Confirm that the following three files exist in the ../Data/ folder: Housing.csv, Geographical_distance_matrix.csv, Similarity_distance_matrix.csv")
        print("2. Confirm that the two matrix files were generated by the preprocessing code for the Housing dataset")
        import traceback
        traceback.print_exc()
        return None, None, None, None, None, None


def evaluate_predictions(y_true, y_pred):
    """Evaluate prediction results"""
    mae = np.mean(np.abs(y_true - y_pred))
    mse = np.mean((y_true - y_pred) ** 2)
    rmse = np.sqrt(mse)
    mape = np.mean(np.abs((y_true - y_pred) / np.maximum(np.abs(y_true), 1e-8))) * 100

    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    r2 = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0

    return {
        'MAE': mae,
        'RMSE': rmse,
        'MAPE': mape,
        'R2': r2,
        'MSE': mse
    }


def save_results(model, X, Y, Y_pred, coords, metrics, out_dir, x_col_names):
    """Save results to output folder"""
    results_df = pd.DataFrame({
        'Coord1': coords[:, 0], 'Coord2': coords[:, 1],
        'Coord3': coords[:, 2], 'Coord4': coords[:, 3],
        'True_price': Y, 'Predicted_price': Y_pred,
        'Residual': Y - Y_pred
    })
    results_df.to_csv(os.path.join(out_dir, 'gsgwr_optimized_results.csv'), index=False)

    n_samples = len(Y)
    for start_idx in range(0, n_samples, 5000):
        end_idx = min(start_idx + 5000, n_samples)
        # Dynamically build column names: intercept + original independent variable names
        coef_cols = ['Intercept'] + x_col_names
        local_coef_batch = pd.DataFrame(
            model.local_coef_[start_idx:end_idx],
            columns=coef_cols
        )
        local_coef_batch['Coord1'] = coords[start_idx:end_idx, 0]
        local_coef_batch['Coord2'] = coords[start_idx:end_idx, 1]
        local_coef_batch['Coord3'] = coords[start_idx:end_idx, 2]
        local_coef_batch['Coord4'] = coords[start_idx:end_idx, 3]

        filename = f'gsgwr_local_coefficients_batch_{start_idx}_{end_idx}.csv'
        local_coef_batch.to_csv(os.path.join(out_dir, filename), index=False)

    pd.DataFrame([metrics]).to_csv(os.path.join(out_dir, 'gsgwr_optimized_metrics.csv'), index=False)


def main_optimized_with_bandwidth_search(out_dir):
    """Main function using bandwidth search"""
    X, Y, D_s, D_a, coords, x_names = load_all_data()

    if X is None:
        print("Data loading failed")
        return

    X_scaler = StandardScaler()
    Y_scaler = StandardScaler()

    X_scaled = X_scaler.fit_transform(X)
    Y_scaled = Y_scaler.fit_transform(Y.reshape(-1, 1)).flatten()

    print("Starting bandwidth optimization search...")
    optimizer = BandwidthOptimizer(batch_size=500)
    best_h_s, best_h_a = optimizer.optimize(X_scaled, Y_scaled, D_s, D_a)

    print(f"\nTraining final model with optimal bandwidths: h_s={best_h_s:.6f}, h_a={best_h_a:.6f}")
    model = GSGWR_Optimized(h_s=best_h_s, h_a=best_h_a, batch_size=500)
    model.fit(X_scaled, Y_scaled, D_s, D_a)

    model.X_scaler = X_scaler
    model.Y_scaler = Y_scaler

    Y_pred_scaled = model.predict(X_scaled)
    Y_pred = model.Y_scaler.inverse_transform(Y_pred_scaled.reshape(-1, 1)).flatten()

    metrics = evaluate_predictions(Y, Y_pred)

    print("\nOptimized model prediction results:")
    print("=" * 40)
    print(f"MAE: {metrics['MAE']:.6f}")
    print(f"RMSE: {metrics['RMSE']:.6f}")
    print(f"MAPE: {metrics['MAPE']:.6f}%")
    print(f"R²: {metrics['R2']:.6f}")

    save_results(model, X, Y, Y_pred, coords, metrics, out_dir, x_names)
    print(f"\nAll results saved to folder: {out_dir}")
    return model


def main_optimized_fixed(out_dir):
    """Main function using fixed bandwidths"""
    X, Y, D_s, D_a, coords, x_names = load_all_data()

    if X is None:
        print("Data loading failed")
        return

    X_scaler = StandardScaler()
    Y_scaler = StandardScaler()

    X_scaled = X_scaler.fit_transform(X)
    Y_scaled = Y_scaler.fit_transform(Y.reshape(-1, 1)).flatten()

    model = GSGWR_Optimized(
        h_s=0.074347,
        h_a=10.504064,
        batch_size=500
    )

    print("Starting training of optimized GSGWR model...")
    model.fit(X_scaled, Y_scaled, D_s, D_a)

    model.X_scaler = X_scaler
    model.Y_scaler = Y_scaler

    Y_pred_scaled = model.predict(X_scaled)
    Y_pred = model.Y_scaler.inverse_transform(Y_pred_scaled.reshape(-1, 1)).flatten()

    metrics = evaluate_predictions(Y, Y_pred)

    print("\nOptimized model prediction results:")
    print("=" * 40)
    print(f"MAE: {metrics['MAE']:.6f}")
    print(f"RMSE: {metrics['RMSE']:.6f}")
    print(f"MAPE: {metrics['MAPE']:.6f}%")
    print(f"R²: {metrics['R2']:.6f}")

    save_results(model, X, Y, Y_pred, coords, metrics, out_dir, x_names)
    print(f"\nAll results saved to folder: {out_dir}")
    return model


if __name__ == "__main__":

    output_folder = './output_housing'
    os.makedirs(output_folder, exist_ok=True)

    print("GSGWR Model Optimized Version")
    print("Please select mode:")
    print("1 - Bandwidth optimization search (recommended, using leave-one-out cross-validation)")
    print("2 - Fixed bandwidth (quick test)")

    choice = input("Enter your choice (1 or 2): ").strip()

    if choice == "1":
        print("Executing bandwidth optimization search (using leave-one-out cross-validation)...")
        main_optimized_with_bandwidth_search(output_folder)
    else:
        print("Executing fixed bandwidth version...")
        main_optimized_fixed(output_folder)
