"""
GSGWR Model Core Estimation Code
Paper: Geographical Similarity and Geographically Weighted Regression (GSGWR): Operationalizing the Second Law of Geography in a Regression Framework by Integrating the First and Third Laws

# Repository Folder Structure (For Reviewers)
Whole repository contains two top-level folders:
1. /GSGWR/ (this code folder)
   - GSGWR_main.py: A standard version for small-to-medium-sized datasets (sample size < 3,000, e.g., zn, Crime, HIV, Depression), which is computationally efficient and concise in code.
   - GSGWR_Housing.py: An optimized batch-processing version specifically designed for large-sample datasets (e.g., Housing), suitable for large-scale data scenarios.
   - Preprocess_GeoMatrix.py: script to generate geographical spatial distance matrix
   - Preprocess_SimMatrix.py: script to generate attribute similarity distance matrix
2. /Data/ (all datasets & matrix outputs, sibling folder of GSGWR)
   - Raw empirical CSV datasets: zn.csv, Crime.csv, HIV.csv,  Depression.csv
   - Geographical_distance_matrix.csv: spatial distance matrix auto-generated by preprocessing code
   - Similarity_distance_matrix.csv: feature similarity distance matrix auto-generated by preprocessing code

# Full Workflow
1. Generate two distance matrix files first
   Run two preprocessing scripts located in /GSGWR/:
   - Run Preprocess_GeoMatrix.py → outputs Geographical_distance_matrix.csv saved to ../Data/
   - Run Preprocess_SimMatrix.py → outputs Similarity_distance_matrix.csv saved to ../Data/
   The two matrix CSV files will be automatically stored into the /Data/ folder.

2. Switch target dataset manually before running this main script
   Open load_all_data() function, locate the MANUAL REPLACE AREA block, modify three file paths:
   ① main_file: target dataset file path (starts with ../Data/, e.g. ../Data/zn.csv)
   ② geo_matrix_file: corresponding geographical distance matrix file in Data folder
   ③ sim_matrix_file: corresponding similarity distance matrix file in Data folder
   All data files are stored in the sibling /Data/ folder, not the same directory as this script.

3. Output storage
   After model fitting finishes, a new folder ./output will be created inside /GSGWR/,
   all local coefficients, prediction results and evaluation metrics will be saved here automatically.
"""
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator
from sklearn.preprocessing import StandardScaler
import warnings
import os

warnings.filterwarnings('ignore')


class GSGWR(BaseEstimator):

    def __init__(self, h_s=1.0, h_a=1.0, tol=1e-6):
        self.h_s = h_s
        self.h_a = h_a
        self.tol = tol
        self.local_coef_ = None
        self.min_cv = None
        self.X_scaler = None
        self.Y_scaler = None

    def _gaussian_kernel(self, d, h):
        return np.exp(-(d ** 2) / (h ** 2))

    def _compute_weights(self, D_s, D_a, h_s, h_a, exclude_idx=None):
        """Compute combined geographical-similarity weight matrix (for cross-validation)"""
        if exclude_idx is not None:
            distances_to_val = D_s[:, exclude_idx]
            similarities_to_val = D_a[:, exclude_idx]

            mask = np.ones(D_s.shape[0], dtype=bool)
            mask[exclude_idx] = False

            train_distances = distances_to_val[mask]
            train_similarities = similarities_to_val[mask]

            W_s_vector = self._gaussian_kernel(train_distances, h_s)
            W_a_vector = self._gaussian_kernel(train_similarities, h_a)
            W_combined = np.diag(W_s_vector * W_a_vector)

        else:
            W_s = self._gaussian_kernel(D_s, h_s)
            W_a = self._gaussian_kernel(D_a, h_a)
            W_combined = W_s * W_a

        return W_combined

    def _compute_weights_for_target(self, D_s, D_a, h_s, h_a, target_idx):
        """Compute weight matrix for a specific target point"""
        distances_to_target = D_s[:, target_idx]
        similarities_to_target = D_a[:, target_idx]

        W_s_vector = self._gaussian_kernel(distances_to_target, h_s)
        W_a_vector = self._gaussian_kernel(similarities_to_target, h_a)
        W_vector = W_s_vector * W_a_vector
        W_combined = np.diag(W_vector)

        return W_combined

    def fit_local_model(self, X, Y, W, exclude_idx=None):
        """Fit local weighted regression model"""
        if exclude_idx is not None:
            mask = np.ones(X.shape[0], dtype=bool)
            mask[exclude_idx] = False
            X_sub = X[mask]
            Y_sub = Y[mask]
        else:
            X_sub = X
            Y_sub = Y

        X_design = np.column_stack([np.ones(X_sub.shape[0]), X_sub])

        try:
            if W.ndim == 2 and W.shape[0] == W.shape[1]:
                W_sqrt = np.sqrt(W)
                X_weighted = W_sqrt @ X_design
                Y_weighted = W_sqrt @ Y_sub
            else:
                W_sqrt = np.sqrt(np.diag(W)) if W.ndim == 2 else np.sqrt(W)
                X_weighted = W_sqrt.reshape(-1, 1) * X_design
                Y_weighted = W_sqrt * Y_sub

            beta, _, _, _ = np.linalg.lstsq(X_weighted, Y_weighted, rcond=None)
            return beta
        except np.linalg.LinAlgError:
            return np.zeros(X_design.shape[1])

    def leave_one_out_cv(self, X, Y, D_s, D_a, h_s, h_a):
        """Leave-one-out cross-validation"""
        n = len(Y)
        total_error = 0
        valid_predictions = 0

        print(f"  Starting LOO-CV: h_s={h_s:.3f}, h_a={h_a:.3f}")

        for i in range(n):
            W = self._compute_weights(D_s, D_a, h_s, h_a, exclude_idx=i)
            beta = self.fit_local_model(X, Y, W, exclude_idx=i)

            if len(beta) > 0 and not np.all(beta == 0):
                X_i = np.concatenate([[1], X[i]])
                y_pred = X_i @ beta
                total_error += (Y[i] - y_pred) ** 2
                valid_predictions += 1

            if (i + 1) % 100 == 0:
                print(f"    Completed {i + 1}/{n} samples for validation")

        if valid_predictions == 0:
            return float('inf')

        return total_error / valid_predictions

    def grid_search(self, X, Y, D_s, D_a, h_s_candidates, h_a_candidates):
        """Grid search for optimal bandwidths"""
        min_cv = float('inf')
        best_h_s, best_h_a = None, None
        cv_results = []

        print("Starting grid search...")
        total_combinations = len(h_s_candidates) * len(h_a_candidates)
        current_combination = 0

        for h_s in h_s_candidates:
            for h_a in h_a_candidates:
                current_combination += 1
                print(f"Progress: {current_combination}/{total_combinations}, testing h_s={h_s:.3f}, h_a={h_a:.3f}")

                cv_score = self.leave_one_out_cv(X, Y, D_s, D_a, h_s, h_a)
                cv_results.append((h_s, h_a, cv_score))

                if cv_score < min_cv:
                    min_cv = cv_score
                    best_h_s, best_h_a = h_s, h_a
                    print(f"  Found better solution: h_s={best_h_s:.3f}, h_a={best_h_a:.3f}, CV={min_cv:.6f}")

        return best_h_s, best_h_a, min_cv

    def adaptive_refinement(self, X, Y, D_s, D_a, best_h_s, best_h_a, min_cv, max_refinements=3):
        """Adaptive refinement search"""
        print("Starting adaptive refinement search...")

        for refinement in range(max_refinements):
            old_min_cv = min_cv
            scale = 0.5 ** (refinement + 1)
            h_s_range = best_h_s * scale
            h_a_range = best_h_a * scale

            fine_h_s = np.linspace(max(0.001, best_h_s - h_s_range), best_h_s + h_s_range, 5)
            fine_h_a = np.linspace(max(0.001, best_h_a - h_a_range), best_h_a + h_a_range, 5)

            fine_h_s = np.unique(fine_h_s)
            fine_h_a = np.unique(fine_h_a)

            print(f"  Refinement round {refinement + 1}:")
            print(f"    h_s search range: {fine_h_s}")
            print(f"    h_a search range: {fine_h_a}")

            if len(fine_h_s) == 0 or len(fine_h_a) == 0:
                print("  Invalid search range, skipping this round")
                break

            best_h_s, best_h_a, min_cv = self.grid_search(X, Y, D_s, D_a, fine_h_s, fine_h_a)

            improvement = old_min_cv - min_cv
            print(f"  Round {refinement + 1} improvement: {improvement:.6f}")

            if abs(improvement) < self.tol:
                print("  Convergence condition met, terminating refinement early")
                break

        return best_h_s, best_h_a, min_cv

    def gsgwr_cv(self, X, Y, D_s, D_a, h_s_candidates, h_a_candidates, max_refinements=3):
        """GSGWR dual-bandwidth cross-validation optimization"""
        print("=== GSGWR Dual-Bandwidth Optimization Started ===")

        best_h_s, best_h_a, min_cv = self.grid_search(X, Y, D_s, D_a, h_s_candidates, h_a_candidates)
        print(f"Coarse grid search result: h_s={best_h_s:.6f}, h_a={best_h_a:.6f}, CV={min_cv:.6f}")

        if max_refinements > 0:
            best_h_s, best_h_a, min_cv = self.adaptive_refinement(
                X, Y, D_s, D_a, best_h_s, best_h_a, min_cv, max_refinements
            )
            print(f"Refined search result: h_s={best_h_s:.6f}, h_a={best_h_a:.6f}, CV={min_cv:.6f}")

        print("=== GSGWR Dual-Bandwidth Optimization Completed ===")
        return best_h_s, best_h_a, min_cv

    def fit(self, X, Y, D_s, D_a, h_s_candidates=None, h_a_candidates=None, max_refinements=2):
        """Fit the model"""
        if h_s_candidates is None:
            h_s_vals = np.percentile(D_s[D_s > 0], [25, 50, 75])
            h_s_candidates = np.linspace(h_s_vals[0], h_s_vals[2], 5)

        if h_a_candidates is None:
            h_a_vals = np.percentile(D_a[D_a > 0], [25, 50, 75])
            h_a_candidates = np.linspace(h_a_vals[0], h_a_vals[2], 5)

        self.h_s, self.h_a, self.min_cv = self.gsgwr_cv(
            X, Y, D_s, D_a, h_s_candidates, h_a_candidates, max_refinements
        )

        print(f"Optimal bandwidth parameters: h_s={self.h_s:.6f}, h_a={self.h_a:.6f}")
        print(f"Minimum cross-validation error: {self.min_cv:.6f}")

        n_samples = X.shape[0]
        n_features = X.shape[1]
        self.local_coef_ = np.zeros((n_samples, n_features + 1))

        print("Fitting full model with optimal bandwidths...")
        for i in range(n_samples):
            W = self._compute_weights_for_target(D_s, D_a, self.h_s, self.h_a, target_idx=i)
            beta = self.fit_local_model(X, Y, W)
            self.local_coef_[i] = beta

            if (i + 1) % 100 == 0:
                print(f"Fitted {i + 1}/{n_samples} local models")

        print("Model fitting completed!")
        return self

    def predict_local(self, X_train, Y_train, D_s_val, D_a_val, X_val):
        n_val = X_val.shape[0]
        y_pred = np.zeros(n_val)

        print(f"Starting prediction on validation set with {n_val} samples...")

        for i in range(n_val):
            distances_to_val = D_s_val[:, i]
            similarities_to_val = D_a_val[:, i]

            W_s_vector = self._gaussian_kernel(distances_to_val, self.h_s)
            W_a_vector = self._gaussian_kernel(similarities_to_val, self.h_a)
            W_vector = W_s_vector * W_a_vector

            X_design = np.column_stack([np.ones(X_train.shape[0]), X_train])
            W_sqrt = np.sqrt(W_vector)

            X_weighted = W_sqrt.reshape(-1, 1) * X_design
            Y_weighted = W_sqrt * Y_train

            try:
                beta, _, _, _ = np.linalg.lstsq(X_weighted, Y_weighted, rcond=None)
                X_val_i = np.concatenate([[1], X_val[i]])
                y_pred[i] = X_val_i @ beta
            except np.linalg.LinAlgError:
                y_pred[i] = np.mean(Y_train)

            if (i + 1) % 10 == 0:
                print(f"    Completed {i + 1}/{n_val} validation predictions")

        return y_pred

    def predict(self, X):
        if self.local_coef_ is None:
            raise ValueError("Model not trained yet. Please call fit() first.")
        if X.shape[0] != self.local_coef_.shape[0]:
            raise ValueError(f"Number of input samples ({X.shape[0]}) does not match number of local models ({self.local_coef_.shape[0]})")

        X_design = np.column_stack([np.ones(X.shape[0]), X])
        y_pred = np.sum(X_design * self.local_coef_, axis=1)
        return y_pred


def load_all_data():
    """Load dataset from sibling /Data/ folder (separated data directory)"""
    try:
        # ====================== MANUAL REPLACE AREA BEFORE RUN ======================
        # [Must manually modify before running, replace with filenames of current experiment]
        # All data files are stored in the sibling folder ../Data/ (not same directory as this script)
        # Main dataset format: first 4 columns = coordinates, 5th column = dependent variable, 6th+ columns = independent variables
        main_file = '../Data/your_data.csv'                         # Example: ../Data/zn5.csv / ../Data/Crime.csv
        geo_matrix_file = '../Data/Geographical_distance_matrix.csv'    # Spatial distance matrix output from preprocessing code
        sim_matrix_file = '../Data/Similarity_distance_matrix.csv'      # Attribute similarity distance matrix output
        # ===========================================================================

        all_data = pd.read_csv(main_file)
        print(f"Current main dataset: {main_file}, shape: {all_data.shape}")
        print("Column names:", all_data.columns.tolist())

        # First 4 columns are coordinate variables
        coords = all_data.iloc[:, 0:4].values
        # 5th column is dependent variable
        Y = all_data.iloc[:, 4].values
        # Columns starting from 6th are independent explanatory variables
        X = all_data.iloc[:, 5:].values
        feature_names = all_data.columns[5:].tolist()

        print(f"Coordinate data shape: {coords.shape}")
        print(f"Dependent variable shape: {Y.shape}")
        print(f"Independent variables shape: {X.shape}")
        print(f"Feature names: {feature_names}")

        n_samples = len(Y)
        print(f"Number of samples: {n_samples}")

        print(f"Reading geographical distance matrix: {geo_matrix_file} ...")
        D_s = pd.read_csv(geo_matrix_file, header=None)
        print(f"Reading similarity distance matrix: {sim_matrix_file} ...")
        D_a = pd.read_csv(sim_matrix_file, header=None)

        print(f"Raw geographical distance matrix shape: {D_s.shape}")
        print(f"Raw similarity distance matrix shape: {D_a.shape}")

        if D_s.shape[0] == n_samples + 1 and D_s.shape[1] == n_samples:
            print("Detected extra header row in geographical distance matrix, removing first row...")
            D_s = D_s.iloc[1:, :]
        if D_a.shape[0] == n_samples + 1 and D_a.shape[1] == n_samples:
            print("Detected extra header row in similarity distance matrix, removing first row...")
            D_a = D_a.iloc[1:, :]

        print("Converting matrices to numeric type...")
        D_s = D_s.apply(pd.to_numeric, errors='coerce')
        D_a = D_a.apply(pd.to_numeric, errors='coerce')

        D_s = D_s.values
        D_a = D_a.values

        print(f"Corrected geographical distance matrix shape: {D_s.shape}")
        print(f"Corrected similarity distance matrix shape: {D_a.shape}")

        if np.any(np.isnan(D_s)):
            print("Warning: geographical distance matrix contains NaN values, filling with 0")
            D_s = np.nan_to_num(D_s)
        if np.any(np.isnan(D_a)):
            print("Warning: similarity distance matrix contains NaN values, filling with 0")
            D_a = np.nan_to_num(D_a)

        # Dimension matching check to avoid dataset-matrix sample mismatch
        if D_s.shape[0] != n_samples or D_s.shape[1] != n_samples:
            raise ValueError(f"Geographical distance matrix dimension mismatch! Main dataset {main_file} has {n_samples} samples, matrix shape {D_s.shape}")
        if D_a.shape[0] != n_samples or D_a.shape[1] != n_samples:
            raise ValueError(f"Similarity distance matrix dimension mismatch! Main dataset {main_file} has {n_samples} samples, matrix shape {D_a.shape}")

        return X, Y, D_s, D_a, coords, feature_names

    except Exception as e:
        print(f"Data loading failed: {e}")
        print("=== Troubleshooting Tips ===")
        print(f"1. Confirm three files exist in ../Data/ folder: {main_file}, {geo_matrix_file}, {sim_matrix_file}")
        print("2. Confirm two matrix CSV files are generated by matching preprocessing scripts for this dataset")
        print("3. Check file names in [MANUAL REPLACE AREA] match actual file names in Data folder exactly")
        print("4. Check dataset column format: first four columns coordinates, fifth dependent variable, rest independent variables")
        import traceback
        traceback.print_exc()
        return None, None, None, None, None, None


def evaluate_predictions(y_true, y_pred):
    """Calculate regression evaluation metrics"""
    mae = np.mean(np.abs(y_true - y_pred))
    mse = np.mean((y_true - y_pred) ** 2)
    rmse = np.sqrt(mse)
    mape = np.mean(np.abs((y_true - y_pred) / np.maximum(np.abs(y_true), 1e-8))) * 100

    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    r2 = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0

    return {
        'MAE': mae,
        'RMSE': rmse,
        'MAPE': mape,
        'R2': r2,
        'MSE': mse
    }


def main():
    # Output folder created inside current /GSGWR/ code directory
    out_dir = './output'
    os.makedirs(out_dir, exist_ok=True)

    result = load_all_data()
    if result[0] is None:
        print("Data loading failed, exiting program")
        return
    X, Y, D_s, D_a, coords, feature_names = result

    X_scaler = StandardScaler()
    Y_scaler = StandardScaler()

    X_scaled = X_scaler.fit_transform(X)
    Y_scaled = Y_scaler.fit_transform(Y.reshape(-1, 1)).flatten()

    model = GSGWR()
    model.fit(X_scaled, Y_scaled, D_s, D_a, max_refinements=2)

    model.X_scaler = X_scaler
    model.Y_scaler = Y_scaler

    print("\n" + "=" * 60)
    print("GSGWR Model Training Completed")
    print("=" * 60)
    print(f"Optimal geographical bandwidth h_s: {model.h_s:.6f}")
    print(f"Optimal similarity bandwidth h_a: {model.h_a:.6f}")
    print(f"Minimum CV value: {model.min_cv:.6f}")

    Y_pred_scaled = model.predict(X_scaled)
    Y_pred = model.Y_scaler.inverse_transform(Y_pred_scaled.reshape(-1, 1)).flatten()

    metrics = evaluate_predictions(Y, Y_pred)

    print("\nEvaluation on all data predictions:")
    print("=" * 40)
    print(f"MAE (Mean Absolute Error): {metrics['MAE']:.6f}")
    print(f"RMSE (Root Mean Squared Error): {metrics['RMSE']:.6f}")
    print(f"MAPE (Mean Absolute Percentage Error): {metrics['MAPE']:.6f}%")
    print(f"R² (Coefficient of Determination): {metrics['R2']:.6f}")
    print(f"MSE (Mean Squared Error): {metrics['MSE']:.6f}")

    all_results = pd.DataFrame({
        'Coord1': coords[:, 0],
        'Coord2': coords[:, 1],
        'True_Value': Y,
        'Predicted_Value': Y_pred,
        'Residual': Y - Y_pred
    })
    all_results.to_csv(os.path.join(out_dir, 'gsgwr_all_data_results.csv'), index=False)

    metrics_df = pd.DataFrame([metrics])
    metrics_df.to_csv(os.path.join(out_dir, 'gsgwr_all_data_metrics.csv'), index=False)

    local_coef_df = pd.DataFrame(
        model.local_coef_,
        columns=['Intercept'] + feature_names
    )
    local_coef_df['Coord1'] = coords[:, 0]
    local_coef_df['Coord2'] = coords[:, 1]
    local_coef_df.to_csv(os.path.join(out_dir, 'gsgwr_local_coefficients_all_data.csv'), index=False)


if __name__ == "__main__":
    main()
